# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghc-7.10.2

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- MonadRandom-0.4.1
- StateVar-1.1.0.2
- adjunctions-4.2.2
- aeson-0.8.1.1
- aeson-extra-0.2.3.0
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- attoparsec-0.13.0.1
- auto-update-0.1.3
- base-orphans-0.4.5
- base64-bytestring-1.0.0.1
- bifunctors-5.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- blaze-textual-0.2.1.0
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- bytestring-conversion-0.3.1
- case-insensitive-1.2.0.5
- cmdargs-0.10.13
- comonad-4.2.7.2
- conduit-1.2.6.1
- conduit-extra-1.1.9.2
- contravariant-1.3.3
- cookie-0.4.1.6
- cryptohash-0.11.6
- cryptohash-conduit-0.1.1
- data-default-class-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- double-conversion-2.0.1.0
- easy-file-0.2.1
- either-4.3.4.1
- esqueleto-2.4.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- file-embed-0.0.9
- free-4.12.1
- hashable-1.2.3.3
- hex-0.1.2
- http-date-0.0.6.1
- http-media-0.6.2
- http-types-0.9
- http2-1.3.1
- iproute-1.7.0
- kan-extensions-4.2.3
- lens-4.13
- lifted-base-0.2.3.6
- lucid-2.9.4
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- monad-logger-0.3.16
- monad-loops-0.4.3
- network-info-0.2.0.8
- optparse-applicative-0.12.0.0
- parallel-3.2.1.0
- path-pieces-0.2.1
- persistent-2.1.6
- persistent-postgresql-2.1.6
- persistent-template-2.1.3.7
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.4.10.0
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.2
- psqueues-0.2.0.3
- reflection-2.1
- resource-pool-0.2.3.2
- resourcet-1.1.7
- safe-0.3.9
- scientific-0.3.4.4
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- servant-0.4.4.5
- servant-docs-0.4.4.5
- servant-lucid-0.4.4.5
- servant-server-0.4.4.5
- silently-1.2.5
- simple-sendfile-0.2.21
- split-0.2.2
- stm-chans-3.0.0.4
- streaming-commons-0.1.15
- string-conversions-0.4
- stringsearch-0.3.6.6
- syb-0.6
- system-filepath-0.4.13.4
- tagged-0.8.2
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.6
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- uuid-1.3.11
- uuid-types-1.0.2
- vault-0.3.0.5
- vector-0.11.0.0
- void-0.7.1
- wai-3.0.5.0
- wai-app-static-3.1.4.1
- wai-extra-3.0.13.1
- wai-logger-2.2.4.1
- warp-3.1.12
- word8-0.1.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.10.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
